dist: trusty
sudo: required

addons:
    sonarqube:
        organization:
        token:
            secure: "kNspG7y3cymGBewUqKRj"
jdk:
    - oraclejdk8
script:
    - sonar-scanner
cache:
    directories:
        - '$HOME/.sonar/cache'
