#!/bin/bash 
TODAY=$(date)
HOST=$(hostname)
# updating wordpress to minor version
echo "<---------            $TODAY  at  $HOST          -------->"
wp core check-update --path=/var/www/html/ --minor --skip-themes=all

# load database update

# change 'hellodorado' to 'helldorado' on all tables before updating options
wp search-replace --all-tables 'http://dev1.websiteserverhost.com/hellodorado' 'https://re7.helldorado.fr'

# update wp options from database
wp option update siteurl 'https://re7.helldorado.fr'
wp option update home 'https://re7.helldorado.fr'
wp option update blogname 'Hell Dorado'
wp option update blogdescription "Les lois éternelles de l'enfer"
wp option update admin_email 'contact.laguilde@helldorado'
wp option update template 'helldorado'
wp option update stylesheet 'helldorado'
